### ISSUE TITLE
内容上下显示不全

### ISSUE THREAD

**Issue by Mooooore** [MarkMindCkm/obsidian-enhancing-mindmap#108]
打开纯文字类型的MD文件,446行60K左右,上面和下面都出现显示不全
文件是从外部复制修改后,通过此插件正常显示,非手动书写
![](https://github.com/Mooooore/Picc/raw/main/Screen%20Shot%202022-11-05%20at%2010.19.53%20AM.jpg)

版本号:
OB1.03   Enhancing-mindmap 0.2.4

**Comment by MarkMindCkm** [comment]
> 打开纯文字类型的MD文件,446行60K左右,上面和下面都出现线条显示不全 文件是从外部复制修改后,通过此插件正常显示,非手动书写 ![](https://github.com/Mooooore/Picc/raw/main/Screen%20Shot%202022-11-05%20at%2010.19.53%20AM.jpg)
> 
> 版本号: OB1.03 Enhancing-mindmap 0.2.4


你可以把文件发给我，我帮你检查一下 ckminder@163.com

**Comment by Mooooore** [comment]
已发!
这是最近刚读的一本书,自己做的摘抄.
教育小朋友真是一门大学问.强烈推荐

**Comment by Mooooore** [comment]
谢谢 大佬MarkMindCkm指点
**原因是插件设置里画布的问题**
由原来的8000设置到最大即可
我就不回复邮件了,写在这里,希望能帮到遇到同样问题的人
