### ISSUE TITLE
Allow user to set maximum node width in setting

### ISSUE THREAD

**Issue by trungng2006** [MarkMindCkm/obsidian-enhancing-mindmap#11]
In my opinion, allowing user to set maximum node width in setting can help them customize their map according to their screen size.
I think it will be very helpful for mobile user.

**Comment by MarkMindCkm** [comment]
you can change max-width of styles to set node max size :

```
.mm-node .mm-node-content {
  padding: 2px 4px;
  max-width: 800px;
  word-break:break-all;
}
```

**Comment by trungng2006** [comment]
I did try adjusting this snippet last night. The box did get smaller, however, the bar stay the same size and the word would overlap each other. 
This is the results when i set max-width to 400px:
![image](https://user-images.githubusercontent.com/71961905/125730194-c569fd95-4753-4ac2-bb85-048e47565b71.png)

I also tried to change word-break to break-word, the problem is still the same. The bar do not adjust according to change in box size:
break-all:
![image](https://user-images.githubusercontent.com/71961905/125730386-99a3ab73-f735-4f87-8358-d11d3657300d.png)
Break-word:
![image](https://user-images.githubusercontent.com/71961905/125730435-d8abc69b-975a-44de-ab0c-94e7bcd44169.png)

**Comment by trungng2006** [comment]
In addition, this adjustment will be more crucial in mobile rather than on computer due to the screen size. 
And it is quite difficult for users to adjust CSS in the mobile environment.

**Comment by MarkMindCkm** [comment]
I think it's a problem of CSS conflict

![test](https://user-images.githubusercontent.com/18719494/125760180-f5553017-344f-4b1e-976f-31565fcac02c.gif)

**Comment by MarkMindCkm** [comment]
Maybe some plug-ins have set the highest height

**Comment by trungng2006** [comment]
I found the problem. 
The map will only adjust after user restart obsidian. 
However, the bar still do not adjust correctly:
![image](https://user-images.githubusercontent.com/71961905/125763613-69d3637f-8995-4a7a-ba15-444bf159ef3a.png)

And the problem is worse when user edit the node:
![image](https://user-images.githubusercontent.com/71961905/125763709-a328c8de-af17-440a-bb9a-2607e9ae1ea6.png)

**Comment by trungng2006** [comment]
Additional information:
On mobile:
I tried word-break: break-word  and it work ok.
However, the problem of node spill over when editing also happen on mobile.

**Comment by trungng2006** [comment]
> ![image](https://user-images.githubusercontent.com/71961905/125763613-69d3637f-8995-4a7a-ba15-444bf159ef3a.png)
> 

I noticed this over lap only happen with link. [link](www.link.com)
usually, if only contain text, then this problem does not happen.

**Comment by MarkMindCkm** [comment]
I have make a new release to fix this issue , https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/releases/tag/0.0.6

I have change  word-break  to  break-word

**Comment by trungng2006** [comment]
Thank you so much!
Last night i also tried a work around:
```
.mm-node .mm-node-content {
  max-width: 700px ;
}
.mm-node.mm-edit-node .mm-node-content{
	max-width: 740px;
}
```

But your way is much better.
Thank you!
