### ISSUE TITLE
install/update to 0.2.5 fails

### ISSUE THREAD

**Issue by koldex** [MarkMindCkm/obsidian-enhancing-mindmap#126]
ror: Request failed, status 404
    at new t (app.js:1:1787032)
    at iW (app.js:1:1787224)
    at app.js:1:1787901
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1

**Comment by MarkMindCkm** [comment]
fix it
