### ISSUE TITLE
Obsidian mindmap in Obsidian Plugins still on 0.0.5 version

### ISSUE THREAD

**Issue by danieltomasz** [MarkMindCkm/obsidian-enhancing-mindmap#14]
The version available through Obsidian community plugins is still 0.0.5 instead of newer one (0.1.0 for example)
Also, the plugin in the community plugin  doesn't display the number of downloads (but maybe it is because it was just  recently included).

**Comment by lishid** [comment]
Seems like manifest.json wasn't updated: https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/main/manifest.json

**Comment by MarkMindCkm** [comment]
thanks
