### ISSUE TITLE
Select several elemts to change their properties

### ISSUE THREAD

**Issue by tur7zeta** [MarkMindCkm/obsidian-enhancing-mindmap#146]
Hi. I'm new using  this nice tool and I didn't find the way to Select several elemts to change their properties at the same time.
Every time I click on the right/left mouse button it doesn't work, even holding press down ctrl/upper case keys.

How can I get it?
Thanks in advice

**Comment by MarkMindCkm** [comment]
Not supported, as the data saved by the plugin is in a simple markdown format and cannot save complex properties

you can try the rich mode of obsidian markmind
 https://github.com/MarkMindCkm/obsidian-markmind

**Comment by tur7zeta** [comment]
Hi again. Now I get a forever subscription.

All I need is to select two nodes, and change their color at the same time. Every time I select several nodes they don't keep selected to act on their properties.

Thank you for your quick replay and support

**Comment by MarkMindCkm** [comment]
Hold down the Ctrl key and right-click on the blank space to select the nodes

**Comment by tur7zeta** [comment]
Thank you very much!! It's work.
Go on with your excellent work.
See you.
