### ISSUE TITLE
Text not visible in dark-mode of some themes

### ISSUE THREAD

**Issue by zFrostz** [MarkMindCkm/obsidian-enhancing-mindmap#16]
The text of the central header in mind-map view is not visible in dark mode of some themes because the white background of the enclosing rectangular box is blending in with the white colored text in dark mode.

I have fixed this issue temporarily by setting the color to something darker in the styles.css :

```
.mm-node.mm-root .mm-node-content {
  font-size: 1.6em;
  padding: 14px 20px;
  border-radius: 0.25rem;
  background: #2E4057;        /*Changed this to darker color (initially set to white)*/
}
```

Now it becomes : 

![after change](https://user-images.githubusercontent.com/81217432/126856511-c9bdc8c2-6c4f-431f-9ef3-9714ceb511e0.png)

Please incorporate this change into the main release of the plugin if it does not interfere with any other aspects or elements of the plugin.

Or alternatively if this method causes problems in other themes where the text appears black then if there could be a way to ensure the text is rendered black regardless of the theme settings, that could work too. However I couldn't figure out how to implement that because I am not very familiar with css.

**Comment by MarkMindCkm** [comment]
I can't do it for every theme. In fact, this is a good way to fix it by change styles

**Comment by zFrostz** [comment]
I understand.. fixing the issue for one theme would create issues for other ones. So I guess its best to leave it at white by default because it supports the default obsidian theme. I'll just change the styles.css to avoid this problem on themes that have it...

Thank you for your time!
