### ISSUE TITLE
Allow user to assign hotkeys to  view mindmap  as markdown or view as mindmap

### ISSUE THREAD

**Issue by MaksimZinovev** [MarkMindCkm/obsidian-enhancing-mindmap#17]
Hi! 
Thank you for a great plugin!

It would be great to be able to assign hotkeys to view mindmap as markdown  or view as mindmap (e.g. switch between markdown and mindmap). 

Maybe I am missing something, but it looks like currently only "Create new mindmap" can be assigned to a hotkey?

Just in case, below are some details of my environment:
- macOS Big Sur 11.4
- Google Chrome Version 92.0.4515.107 (Official Build) (arm64)
- ObsidianMD v0.12.10
- Enhancing  mindmap plugin v.0.1.1

![aerofiler-qa - Obsidian v0 12 10 2021-07-27 18-42](https://user-images.githubusercontent.com/53397443/127124322-6b8fbc36-972b-438b-869a-86d31a0c1c4a.jpg)

Thanks.

**Comment by johans3** [comment]
Converting these 2 plugins in a toggle would be great as well

**Comment by MarkMindCkm** [comment]
https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/releases/tag/0.1.7
