### ISSUE TITLE
Allow user to preserve markdown structure or use lists instead of headings

### ISSUE THREAD

**Issue by MaksimZinovev** [MarkMindCkm/obsidian-enhancing-mindmap#18]
Thank you for great plugin!

My feature request is to allow user to preserve markdown format after file was edited as a mindmap. 

Here is an example to illustrate:
1. Create  markdown file 
```
- mindmap-plugin
  - item 1
  - item 2
  - item 3
```
2. Open the file as mindmap.
3. Add at least one node - a child of item 3
4. Open as markdown

**Result:** 
```
# mindmap-plugin
  ## item 1
  ## item 2
  ## item 3
    - item 31
```  

**Desired result:** 
```
- mindmap-plugin
  - item 1
  - item 2
  - item 3
    - item 31

```

https://user-images.githubusercontent.com/53397443/127127645-f3057861-3ddf-4674-bea6-309138372c69.mp4

Just in case, below are some details of my environment:
- macOS Big Sur 11.4
- Google Chrome Version 92.0.4515.107 (Official Build) (arm64)
- ObsidianMD v0.12.10
- Enhancing  mindmap plugin v.0.1.1

**Comment by Pvazevedo** [comment]
This still happening. 
I prefer to edit in markdown to prevent this changing until fix.

**Comment by MarkMindCkm** [comment]
> This still happening.
> I prefer to edit in markdown to prevent this changing until fix.

please select 0 level in setting tab
