### ISSUE TITLE
Cannot toggle to mindmap view

### ISSUE THREAD

**Issue by cobblepot1** [MarkMindCkm/obsidian-enhancing-mindmap#21]
I'm very excited about this plug-in! But strangely, after installation, I can use it to create a new mindmap but I don't see the command to view an existing markdown file as a mindmap, either in the command palette or in the File Options. It must be installed, since I see it in the plug-ins and can create and view a new file as a mindmap. Any help appreciated. I have disabled all other non-core plug-ins. Obsidian 0.12.12 and enhancing-mindmap 0.1.1, Win 10.

Viewing a markdown file:
![image](https://user-images.githubusercontent.com/65119937/128586805-414a332d-bb44-4f30-8dfe-4ad1ae1c459b.png)

Command palette:
![image](https://user-images.githubusercontent.com/65119937/128586779-5c252b61-5af8-4662-8bd9-7ff3d31426bf.png)

But when viewing a new mindmap, it does show view as markdown:
![image](https://user-images.githubusercontent.com/65119937/128586760-266f57cb-2488-47f3-bf89-39f4c73db360.png)

**Comment by MarkMindCkm** [comment]
add yaml  to the start of markdown file :

```
---

mindmap-plugin: basic

---
```

**Comment by cobblepot1** [comment]
I tried that, still didn't get a 'view as map' toggle in the command palette or 'more options' menu.

The plugin intends that the user must manually add that yaml to the start of every markdown file I want to be able to view as a mindmap? Or does that go in some config file?

I recommend adding this info to the readme file either way.

**Comment by MarkMindCkm** [comment]
add yaml to the start of markdown file ，then:

![111](https://user-images.githubusercontent.com/18719494/128597433-37527d52-3eff-489e-a28c-c0b4bbe6df35.png)

**Comment by Freshman721** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/88606176/128621070-3b63abc6-020b-4f73-849c-bc33197772c7.png">
Still can't find it...

**Comment by cobblepot1** [comment]
Is there any way to make 'Open as markdown' and 'Open as mindmap board' appear in the same place on the menu? That's what was confusing me.

And I'm not a developer, so I can't help with that, but where to make suggestions for features, help with documentation, translation, etc.? One e.g. I'd change 'Open as mindmap board' to 'Open as mindmap'
