### ISSUE TITLE
能否支持文档混排

### ISSUE THREAD

**Issue by smallslime** [MarkMindCkm/obsidian-enhancing-mindmap#24]
![image](https://user-images.githubusercontent.com/1252034/130432269-e01db0ae-7bc6-4fa7-ab53-59760106a5e5.png)

像这样，预览时，直接内存生成图，插入文档中

**Comment by MarkMindCkm** [comment]
目前尚不支持，不过您可以使用obsidian plantuml 插件，应该支持这种嵌入语法
