### ISSUE TITLE
Add the ability to copy + paste a branch in mindmap mode 

### ISSUE THREAD

**Issue by trungng2006** [MarkMindCkm/obsidian-enhancing-mindmap#29]
Currently, user need to switch to markdown mode to copy/paste the bullet points, then turn back to mindmap mode.

2ndly,I think this functionality could also be implement to copy paste between map, instead of just within a map.

**Comment by tastrian** [comment]
表示同样需要这个功能，只要有了它，我就真的可以抛弃xmind了

**Comment by tastrian** [comment]
再来看一眼，期待这个功能；
我几乎都想自己用ahk来写了…把内容用处理文本添加的方式，添加进入md文档……
