### ISSUE TITLE
Only add node is visible in either mode

### ISSUE THREAD

**Issue by Cmhorn** [MarkMindCkm/obsidian-enhancing-mindmap#47]
None of the additional features that enable relationships, summaries, et al are visible. 

![mmrich](https://user-images.githubusercontent.com/50580012/141679882-a4129675-8742-4f6f-bde7-9764a634ae81.png)

Obsidian v0.13.2
PopOS 21.04

**Comment by Cmhorn** [comment]
Change layout doesn't work.

**Comment by MarkMindCkm** [comment]
> Change layout doesn't work.

You should use obsidian markmind plugins

https://github.com/MarkMindCkm/obsidian-markmind

This plugin  support only base mind map festures

**Comment by Cmhorn** [comment]
Good point. Sorry for the error.
