### ISSUE TITLE
Export the mindmap

### ISSUE THREAD

**Issue by kosnik-ng** [MarkMindCkm/obsidian-enhancing-mindmap#50]
Hello,
Great job on this plugin.
Is it possible to export the mind map?
If not, is this a possible feature?

**Comment by kosnik-ng** [comment]
Thanks for the export feature, and how quickly you added it.
I didn't know if I should create a new issue or use this one. If you would have preferred a new issue, sorry.


If I may say so, I have noticed :
- If we work with a dark theme, I use "Solarized" dark in my vault. When exporting, the text is displayed following the theme colour, so sometimes you get white text on a white background.
- If you include a file other than markdown or image with for example ![[file.pdf]], the export doesn't work, without an error message being displayed. I have observed this, with .jpeg and .png working and .pdf and .svg not working.

**Comment by MarkMindCkm** [comment]
> Thanks for the export feature, and how quickly you added it. I didn't know if I should create a new issue or use this one. If you would have preferred a new issue, sorry.
> 
> If I may say so, I have noticed :
> 
> * If we work with a dark theme, I use "Solarized" dark in my vault. When exporting, the text is displayed following the theme colour, so sometimes you get white text on a white background.
> * If you include a file other than markdown or image with for example ![[file.pdf]], the export doesn't work, without an error message being displayed. I have observed this, with .jpeg and .png working and .pdf and .svg not working.

not support ![[ pdf /svg /mp4 ]] , only support image

**Comment by kosnik-ng** [comment]
Okay, thanks for the reply.

**Comment by GreenHatHG** [comment]
Hi. Is it possible to export as an image.

**Comment by MarkMindCkm** [comment]
> Hi. Is it possible to export as an image. @MarkMindCkm

This is a image in fact  , you can open it and right click  save it to a image
