### ISSUE TITLE
Can the mind map embedded with in another markdown file?

### ISSUE THREAD

**Issue by AndyLiu9** [MarkMindCkm/obsidian-enhancing-mindmap#52]
Now if I use ![[mindmap]] in another markdown file, the mind map is shown in plain markdown text. But I want it be rendered in mind map view.

**Comment by ToUpgrade** [comment]
just consider an embedded window but not the whole page, I think this is a common use case to conjoin mind map to enhance the media of obsidian.

**Comment by MarkMindCkm** [comment]
you can try obsidian markmind plugin , it has support this feature
