### ISSUE TITLE
从xmind等其它软件，粘贴到markmind

### ISSUE THREAD

**Issue by tastrian** [MarkMindCkm/obsidian-enhancing-mindmap#56]
希望可以从xmind等其它思维导图软件，用ctrl+c，ctrl+v的方式，把选中的分支，粘贴过来；
用ahk实现的思路大概是：
1. 把xmind以tab分割的几行字符，转化为markdown的格式；
2. 在当前markmind文档里，定位到选中字段的那一行，将字符串插入；

**Comment by MarkMindCkm** [comment]
> 希望可以从xmind等其它思维导图软件，用ctrl+c，ctrl+v的方式，把选中的分支，粘贴过来； 用ahk实现的思路大概是：
> 
> 1. 把xmind以tab分割的几行字符，转化为markdown的格式；
> 2. 在当前markmind文档里，定位到选中字段的那一行，将字符串插入；

会支持导入 xmind zen 文件 , 复制毕竟格式方面有兼容问题

**Comment by MarkMindCkm** [comment]
现在支持导入xmind zen 文件了
