### ISSUE TITLE
激活码没反应怎么办

### ISSUE THREAD

**Issue by zhwly** [MarkMindCkm/obsidian-enhancing-mindmap#57]
我付的是方案2，得到激活码后直接在手机版obsidian上用，填在哪都没用。怎么办？

![Screenshot_2022-01-02-23-35-48-23](https://zhwly.coding.net/p/tuku3/d/image/git/raw/master/Screenshot_2022-01-02-23-35-48-23.jpg)

![Screenshot_2022-01-02-23-35-58-58](https://zhwly.coding.net/p/tuku3/d/image/git/raw/master/Screenshot_2022-01-02-23-35-58-58.jpg)

**Comment by zhwly** [comment]
![Screenshot_2022-01-02-23-38-15-54](https://zhwly.coding.net/p/tuku3/d/image/git/raw/master/Screenshot_2022-01-02-23-38-15-54.jpg)

![Screenshot_2022-01-02-23-38-33-13](https://zhwly.coding.net/p/tuku3/d/image/git/raw/master/Screenshot_2022-01-02-23-38-33-13.jpg)

**Comment by MarkMindCkm** [comment]
> 我付的是方案2，得到激活码后直接在手机版obsidian上用，填在哪都没用。怎么办？
> 
> ![Screenshot_2022-01-02-23-35-48-23](https://camo.githubusercontent.com/be3e9eac24bb091c4992e451c741c6b932bcb5fba86218f2b0836553b92fb46a/68747470733a2f2f7a68776c792e636f64696e672e6e65742f702f74756b75332f642f696d6167652f6769742f7261772f6d61737465722f53637265656e73686f745f323032322d30312d30322d32332d33352d34382d32332e6a7067)
> 
> ![Screenshot_2022-01-02-23-35-58-58](https://camo.githubusercontent.com/57c2b173d5466916d39e1236e5d152cfee111693399dbbfc84201ecdc8b9c380/68747470733a2f2f7a68776c792e636f64696e672e6e65742f702f74756b75332f642f696d6167652f6769742f7261772f6d61737465722f53637265656e73686f745f323032322d30312d30322d32332d33352d35382d35382e6a7067)

在电脑版上使用，重启一下，可以自动生成移动端激活码
