### ISSUE TITLE
what a stupid mod!!Fuck u!!!

### ISSUE THREAD

**Issue by UpDownXH** [MarkMindCkm/obsidian-enhancing-mindmap#68]
It changed my markdown's format!!!!!!!!!!!! and I havent return back!!

**Comment by UpDownXH** [comment]
and it token away picture's urls!!!

**Comment by UpDownXH** [comment]
some content has disappeared!

**Comment by MarkMindCkm** [comment]
> some content has disappeared!

You can use the recovery function and you  are so sick!
