### ISSUE TITLE
YAML and comments get deleted when editing in mindmap view

### ISSUE THREAD

**Issue by Akon00102329** [MarkMindCkm/obsidian-enhancing-mindmap#76]
I want to have a YAML attribute to state the topic of the mindmap. I tried both putting it inside the YAML and on the frontmatter, but in both cases, it gets deleted when editing on the mindmap (adding nodes, moving nodes, collapsing nodes, etc)

**Comment by nibivid** [comment]
is it possiable to add yaml for the mindmap  now
