### ISSUE TITLE
failed to load your plugin

### ISSUE THREAD

**Issue by Phuntsok1973** [MarkMindCkm/obsidian-enhancing-mindmap#8]
Hi
I failed to load your plugin after manual installation on my Mac. Always get this message from obsidian when i try to activate it. Any help? version 0.12.5

**Comment by MarkMindCkm** [comment]
please download main.js  styles.css ,mainifest.json

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/releases/tag/0.0.4

**Comment by Phuntsok1973** [comment]
Thank you! It works now

С уважением,
Андрей Плешивцев
10 июля 2021 г., 16:05 +0300, mark ***@***.***>, писал:
