### ISSUE TITLE
鼠标拖拽功能失效了？

### ISSUE THREAD

**Issue by zhao414** [MarkMindCkm/obsidian-enhancing-mindmap#83]
SYSTEM INFO:
	Obsidian version: v0.14.10
	Installer version: v0.13.31
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz
	Snippets enabled: 10
	Safe mode: off
	Plugins installed: 18
	Plugins enabled: 1
		1: Enhancing Mindmap

字面意思：无法通过鼠标拖拽改变节点位置。
1. 选中某一项。
2. 鼠标拖动到指定位置，出现箭头
3. 松开鼠标，选中项还在原来位置。

**Comment by MarkMindCkm** [comment]
> SYSTEM INFO: Obsidian version: v0.14.10 Installer version: v0.13.31 Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0 Live preview: on Legacy editor: off Base theme: dark Community theme: Blue Topaz Snippets enabled: 10 Safe mode: off Plugins installed: 18 Plugins enabled: 1 1: Enhancing Mindmap
> 
> 字面意思：无法通过鼠标拖拽改变节点位置。
> 
> 1. 选中某一项。
> 2. 鼠标拖动到指定位置，出现箭头
> 3. 松开鼠标，选中项还在原来位置。

我需要升级一下obsidian版本测试一下，这个版本的obsidian 拖拽好像有点问题

**Comment by zhao414** [comment]
谢谢回复。
看到 Lishid 的回复了。
我等下个版本再试试。

**Comment by MarkMindCkm** [comment]
0.14.13 可以了

**Comment by zhao414** [comment]
Thanks!
