### ISSUE TITLE
【bug】something went wrong when image included - error:【Object event】

### ISSUE THREAD

**Issue by chinobing** [MarkMindCkm/obsidian-enhancing-mindmap#88]
![image](https://user-images.githubusercontent.com/27722028/173719399-966f628f-0d73-41a3-b705-1ed68cc546fc.png)

当mardkown中包含了 `![]()` 图片， 导出html的时候就会出现【Object event】这个错误信息， 不论是这个插件还是另外一个付费插件markmind都是一样； 但是，没有含图片的markdown输出mindmap html是正常的。

**Comment by MarkMindCkm** [comment]
> ![image](https://user-images.githubusercontent.com/27722028/173719399-966f628f-0d73-41a3-b705-1ed68cc546fc.png)
> 
> 当mardkown中包含了 `![]()` 图片， 导出html的时候就会出现【Object event】这个错误信息， 不论是这个插件还是另外一个付费插件markmind都是一样； 但是，没有含图片的markdown输出mindmap html是正常的。

目前导出思维导图图片不支持网络图片，只支持本地图片，原因是 canvas 限制跨域操作，obsidian 也限制

**Comment by chinobing** [comment]
原来这样，我的markdown确实全部都是网络图片，谢谢哈
