### ISSUE TITLE
更多选项中没有“打开为思维导图”选项

### ISSUE THREAD

**Issue by Forgoys** [MarkMindCkm/obsidian-enhancing-mindmap#89]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/47031885/177463868-d3682897-c168-4086-a623-43428a1c42e6.png">
直接使用命令调用“切换为markdown或mindmap形式“也无反应。

安装插件后已重启过Obsidian。

**Comment by MarkMindCkm** [comment]
在文件头部有没有这个

```
---

mindmap-plugin: basic

---
```

**Comment by Forgoys** [comment]
加上以后可以了，感谢～

**Comment by Forgoys** [comment]
加上以后可以了，感谢～
