### ISSUE TITLE
Allow additional color choices for bold and italics

### ISSUE THREAD

**Issue by trungng2006** [MarkMindCkm/obsidian-enhancing-mindmap#9]
I think this will also help the user to scan their map faster. The user can use their peripheral vision to focus on the color part.
![image](https://user-images.githubusercontent.com/71961905/125424803-e00ce9a3-11e5-4d97-96cc-45f90829bb37.png)

The current version of the bold is a bit hard for the user to recognize the important point.
![image](https://user-images.githubusercontent.com/71961905/125425088-e4db7f1c-a539-4cd5-a0e6-4e715a05ec53.png)

**Comment by MarkMindCkm** [comment]
You can customize some CSS to change the appearance

**Comment by trungng2006** [comment]
Thank you for your prompt reply!
I tried with 
```
.mm-strong {
	color: var(--neutral-aqua) !important;
	}
```
And 
```
.mm-node-content,
.cm-strong,
.markdown-preview-section strong{
	color: var(--neutral-aqua) !important;
	}
```
```
.mm-node-content.markdown-preview-section strong{
	color: var(--neutral-aqua);}
```
And other combination, but its not working yet. Could you help guide me on which elements should i target?

**Comment by trungng2006** [comment]
I got it.
```
.mm-node-content strong {
    font-weight: 600 !important;
    color: #ff0000 !important;
}
```
