### ISSUE TITLE
Mindmap Automatically Closing File explorer 

### ISSUE THREAD

**Issue by nibivid** [MarkMindCkm/obsidian-enhancing-mindmap#90]
![image](https://user-images.githubusercontent.com/25265126/179160969-79551033-aad5-4802-ba2b-374ebc7b0219.png)
![image](https://user-images.githubusercontent.com/25265126/179161010-dc2fee92-300d-4682-8992-06458b825450.png)

Hai guys am facing this issue since the past few days, I think this can be because of the new obsidian update.  So while opening the mindmap on the folder the file explorer is closing and mind map is opened over the file explorer panel. This is not normal behavior , usually, when the mindmap is created inside a folder by right-clicking on the folder a new mindmap is created over notes . I had a similar problem with kanban application but now its working fine. But Enhancing mindmap got this issue. 

https://user-images.githubusercontent.com/25265126/179162396-ffcf7d15-bbc1-4969-a2bd-f0d4c53427cd.mp4

**Comment by fthibaud** [comment]
Hi all,

I am experiencing exactly the same unexpected behaviour. It occurs both under Linux and under Windows. I agree with @nibivid, I have the feeling that it appeared after the latest Obsidian release (0.15.9). I guess it can help.

Good day

**Comment by nibivid** [comment]
Thanks for the new update man, problems fixed
