### ISSUE TITLE
Where can I find method for parsing markdown and turning into data structure behind the map?

### ISSUE THREAD

**Issue by lofti198** [MarkMindCkm/obsidian-enhancing-mindmap#91]
Hi! Cool plugin! Where can I find method for parsing markdown and turning into data structure behind the map? Just wanna add some functionaily?

**Comment by MarkMindCkm** [comment]
https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/5806e4a2c8563cbb7e823857525e3c23c939aac6/src/markmapLib/markmap-lib/dist/browser/index.js#L8838

**Comment by lofti198** [comment]
Thank you!
