### ISSUE TITLE
BUG-导出为HTML的Bug与优化

### ISSUE THREAD

**Issue by 18AlexHua18** [MarkMindCkm/obsidian-enhancing-mindmap#99]
插件导出为HTML的时候没有看到选项卡可以选择，仅仅在快捷键设置里看到可以导出为HTML
并且实测黑色的Obsidian界面导出的字体为白色，在网页的HTML内可见度不够高
![截屏2022-10-09 下午6 56 04](https://user-images.githubusercontent.com/42309305/194752916-bbfcf4a0-34fb-4e2f-bdd4-52d1b3d2abbc.jpg)
仔细看是白色的字的
感谢作者

**Comment by MarkMindCkm** [comment]
obsidian  改成 白色主题  就行了

**Comment by 18AlexHua18** [comment]
> obsidian 改成 白色主题 就行了

是的但是每次导出都需要寻找快捷键并且在设置中修改主题
有些繁琐
感谢作者付出：）
